Make offload example with OLTP
doublecloud/terraform-provider-doublecloud pull request #47
Opened 2023-10-20 14:27 UTC by laskoviymishka

2023-10-20 17:24 UTC, velom requested changes

2023-10-20 17:24 UTC, velom commented on example_projects/transfer/offload_oltp/README.md
> +Let’s start with a [`m](http://main.tf)ain.tf`, usually it contains providers definition, nothing more:
wrong formation

2023-10-20 17:24 UTC, velom commented on example_projects/transfer/offload_oltp/README.md
> +  endpoint       = "api.double.cloud:443"
remove endpoint parameter, end customer doesn't need it

2023-10-20 17:24 UTC, velom commented on example_projects/transfer/offload_oltp/README.md
> +To enable clickhouse we need to create a network were to put it. For this example I choose [BYOA](https://double.cloud/blog/posts/2022/12/bring-your-own-account/) network, so it can be easily peered
BYOC

2023-10-20 17:24 UTC, velom commented on example_projects/transfer/offload_oltp/README.md
> +  doublecloud_controlplane_account_id = data.aws_caller_identity.self.account_id
according the [documentation](https://registry.terraform.io/modules/doublecloud/doublecloud-byoc/aws/latest?tab=inputs) you don't need to set `doublecloud_controlplane_account_id`

2023-10-20 17:24 UTC, velom commented on example_projects/transfer/offload_oltp/README.md
> +  name        = "dwg"
resource has name "dwh", cluster has name "dwg"

2023-10-20 17:24 UTC, velom commented on example_projects/transfer/offload_oltp/README.md
> +```jsx
hcl

2023-10-20 17:43 UTC, laskoviymishka commented on example_projects/transfer/offload_oltp/README.md
> +To enable clickhouse we need to create a network were to put it. For this example I choose [BYOA](https://double.cloud/blog/posts/2022/12/bring-your-own-account/) network, so it can be easily peered
article refer to this concept as BYOA 🍡

2023-10-23 09:03 UTC, velom approved these changes

2023-10-23 09:06 UTC, merged