DOCS-229 fix resource example
doublecloud/terraform-provider-doublecloud pull request #71
Opened 2024-01-25 15:41 UTC by ivoninskii

2024-01-25 19:32 UTC, laskoviymishka approved these changes

2024-01-25 19:33 UTC, laskoviymishka commented on examples/resources/doublecloud_kafka_cluster/resource.tf
>    name = "example-clickhouse"
name = "example-clickhouse" ->   name = "example-kafka"

2024-01-25 19:33 UTC, laskoviymishka commented on examples/resources/doublecloud_kafka_cluster/resource.tf
>    name = "example-clickhouse"
i think whole this resource is a clickhouse not kafka

2024-01-25 20:02 UTC, laskoviymishka requested changes
tf-file need to be changed

2024-01-29 10:59 UTC, laskoviymishka approved these changes

2024-05-07 15:01 UTC, thameezb approved these changes

2024-06-14 17:03 UTC, closed without merging